apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: database
spec:
  replicas: 2
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: timescaledb-configmap
          volumeMounts:
            - mountPath: /var/lib/timescaledb/data
              # - mountPath: /var/lib/postgresql/data/pgdata # Default
              name: timescaledb-storage
      volumes:
        - name: timescaledb-storage
          persistentVolumeClaim:
            claimName: timescaledb-pvc
