apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-configmap
  namespace: database
  labels:
    app: timescaledb
data:
  POSTGRES_DB: timescaledb
  POSTGRES_USER: admin
  PGDATA: /var/lib/timescaledb/data
